// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityAPI.Data;

namespace UniversityAPI.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20210419154236_newData")]
    partial class newData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniversityAPI.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Established")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Universities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "DUT",
                            Address = "Đà Nẵng",
                            Established = new DateTime(1975, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bách khoa Đà Nẵng"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "DUE",
                            Address = "Đà Nẵng",
                            Established = new DateTime(1975, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kinh tế Đà Nẵng"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "UFL",
                            Address = "Đà Nẵng",
                            Established = new DateTime(2002, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ngoại Ngữ Đà Nẵng"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "UTE",
                            Address = "Đà Nẵng",
                            Established = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sư phạm kĩ thuật Đà Nẵng"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "UED",
                            Address = "Đà Nẵng",
                            Established = new DateTime(1994, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sư phạm Đà Nẵng"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "SMP",
                            Address = "Đà Nẵng",
                            Established = new DateTime(2007, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Khoa Y Dược Đà Nẵng"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "VKU",
                            Address = "Đà Nẵng",
                            Established = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CNTT Việt-Hàn Đà Nẵng"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
